"use client";

import { ColumnDef } from "@tanstack/react-table";
import { Badge } from "@/components/ui/badge";
import { 
  Building2, 
  MoreHorizontal, 
  Edit, 
  Trash, 
  Eye,
  Info
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";

// This type should eventually be generated by Supabase CLI or defined in a types file
export type Apartment = {
  id: string;
  unit_name: string;
  unit_number: string;
  floor: number;
  type: "STUDIO" | "ONE_BEDROOM" | "TWO_BEDROOM" | "THREE_BEDROOM";
  monthly_rent: number;
  status: "VACANT" | "OCCUPIED" | "MAINTENANCE" | "ARCHIVED";
  created_at: string;
};

export const columns: ColumnDef<Apartment>[] = [
  {
    accessorKey: "unit_name",
    header: "Unit Name",
    cell: ({ row }) => {
      const apartment = row.original;
      return (
        <div className="flex items-center gap-3">
          <div className="h-9 w-9 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-500">
            <Building2 className="h-5 w-5" />
          </div>
          <div className="flex flex-col">
            <span className="font-semibold text-white">{apartment.unit_name}</span>
            <span className="text-xs text-slate-500">Unit {apartment.unit_number} • Level {apartment.floor}</span>
          </div>
        </div>
      );
    },
  },
  {
    accessorKey: "type",
    header: "Type",
    cell: ({ row }) => (
      <div className="font-medium text-slate-300">
        {row.getValue("type")?.toString().replace("_", " ")}
      </div>
    ),
  },
  {
    accessorKey: "monthly_rent",
    header: "Rent",
    cell: ({ row }) => {
      const amount = parseFloat(row.getValue("monthly_rent"));
      const formatted = new Intl.NumberFormat("en-GH", {
        style: "currency",
        currency: "GHS",
      }).format(amount);
      return <div className="font-bold text-white">{formatted}</div>;
    },
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => {
      const status = row.getValue("status") as string;
      return (
        <Badge 
          className={cn(
            "font-bold px-2.5 py-0.5 rounded-full border-0",
            status === "VACANT" ? "bg-emerald-500/10 text-emerald-500" :
            status === "OCCUPIED" ? "bg-blue-500/10 text-blue-500" :
            status === "MAINTENANCE" ? "bg-amber-500/10 text-amber-500" :
            "bg-slate-500/10 text-slate-500"
          )}
        >
          {status}
        </Badge>
      );
    },
  },
  {
    id: "actions",
    cell: ({ row }) => {
      const apartment = row.original;

      return (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="h-8 w-8 p-0 text-slate-500 hover:text-white hover:bg-slate-800">
              <span className="sr-only">Open menu</span>
              <MoreHorizontal className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="bg-slate-900 border-slate-800 text-slate-300 w-48">
            <DropdownMenuLabel>Actions</DropdownMenuLabel>
            <DropdownMenuSeparator className="bg-slate-800" />
            <DropdownMenuItem className="gap-2 focus:bg-slate-800 focus:text-white cursor-pointer">
              <Eye className="h-4 w-4" /> View Details
            </DropdownMenuItem>
            <DropdownMenuItem className="gap-2 focus:bg-slate-800 focus:text-white cursor-pointer">
              <Edit className="h-4 w-4" /> Edit Apartment
            </DropdownMenuItem>
            <DropdownMenuItem className="gap-2 focus:bg-slate-800 focus:text-white cursor-pointer">
              <Info className="h-4 w-4" /> Utility Rates
            </DropdownMenuItem>
            <DropdownMenuSeparator className="bg-slate-800" />
            <DropdownMenuItem className="gap-2 text-red-400 focus:bg-red-400/10 focus:text-red-400 cursor-pointer">
              <Trash className="h-4 w-4" /> Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      );
    },
  },
];
