import { NextResponse } from 'next/server';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  renderToStream,
} from '@react-pdf/renderer';
import { getAgreementById } from '@/actions/agreements';
import { format } from 'date-fns';

const styles = StyleSheet.create({
  page: { flexDirection: 'column', backgroundColor: '#FFFFFF', padding: 40, fontFamily: 'Helvetica' },
  header: { fontSize: 24, textAlign: 'center', marginBottom: 5, fontWeight: 'bold' },
  subHeader: { fontSize: 12, textAlign: 'center', marginBottom: 20, color: '#666666' },
  section: { margin: 10, padding: 10, flexGrow: 1 },
  text: { fontSize: 11, marginBottom: 15, lineHeight: 1.5 },
  boldText: { fontWeight: 'bold', fontSize: 13, marginBottom: 5 },
  signatures: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 50 },
  sigBlock: { width: '40%', borderTop: '1px solid #000', paddingTop: 10, textAlign: 'center' },
  sigImage: { height: 40, objectFit: 'contain', marginBottom: 5, marginLeft: 'auto', marginRight: 'auto' },
  sigText: { fontSize: 10, color: '#333333' },
});

// A pure React component specifically for server-side PDF generation
const AgreementDocumentPDF = ({ agreement, tenant, apartment }: any) => {
  const leaseStart = new Date(agreement.lease_start);
  const leaseEnd = new Date(agreement.lease_end);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Residential Tenancy Agreement</Text>
        <Text style={styles.subHeader}>Generated by PILAS Properties Management</Text>
        
        <View style={styles.section}>
          <Text style={styles.text}>
            THIS TENANCY AGREEMENT is made on this {format(new Date(agreement.created_at), 'do')} day 
            of {format(new Date(agreement.created_at), 'MMMM, yyyy')}, by and between PILAS Properties 
            Management (hereinafter referred to as the "Landlord"), and {tenant?.email} (hereinafter referred 
            to as the "Tenant").
          </Text>
          
          <Text style={styles.boldText}>1. Premises</Text>
          <Text style={styles.text}>
            The Landlord hereby agrees to lease to the Tenant the premises located at Unit {apartment?.unit_number} 
            ({apartment?.room_number}), {apartment?.unit_name}, {apartment?.type?.replace('_', ' ')}.
          </Text>

          <Text style={styles.boldText}>2. Term of Tenancy</Text>
          <Text style={styles.text}>
            The term of this lease shall commence on {format(leaseStart, 'MMMM do, yyyy')} and 
            shall terminate on {format(leaseEnd, 'MMMM do, yyyy')}.
          </Text>

          <Text style={styles.boldText}>3. Rent & Deposits</Text>
          <Text style={styles.text}>
            The Tenant agrees to pay the Landlord a base monthly rent of GH₵ {agreement.rent_amount?.toLocaleString()} 
            payable in advance. A required security deposit of GH₵ {agreement.security_deposit?.toLocaleString()} is 
            required prior to occupancy.
          </Text>

          <Text style={styles.boldText}>4. Maintenance</Text>
          <Text style={styles.text}>
            The Tenant shall be responsible for payment of all utilities including electricity, water, and internet. 
            The Tenant is expected to maintain the premises in a clean, sanitary condition.
          </Text>
          
          <View style={styles.signatures}>
             <View style={styles.sigBlock}>
                {agreement.admin_signature_url ? (
                  <Image src={agreement.admin_signature_url} style={styles.sigImage} />
                ) : (
                  <Text style={{...styles.sigText, marginBottom: 10}}>Pilas Admin</Text>
                )}
                <Text style={styles.sigText}>Landlord / Management Agent</Text>
                <Text style={styles.sigText}>Date: {format(new Date(agreement.admin_signed_at || new Date()), 'MMM dd, yyyy')}</Text>
             </View>
             
             <View style={styles.sigBlock}>
                {agreement.tenant_signature_url ? (
                  <Image src={agreement.tenant_signature_url} style={styles.sigImage} />
                ) : (
                  <Text style={{...styles.sigText, marginBottom: 10}}>Awaiting Signature</Text>
                )}
                <Text style={styles.sigText}>Tenant Digital Signature</Text>
                <Text style={styles.sigText}>Date: {agreement.signed_at ? format(new Date(agreement.signed_at), 'MMM dd, yyyy') : '—'}</Text>
             </View>
          </View>
        </View>
      </Page>
    </Document>
  );
};

export const dynamic = 'force-dynamic';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'Missing agreement ID' }, { status: 400 });
  }

  const agreement = await getAgreementById(id);
  
  if (!agreement) {
    return NextResponse.json({ error: 'Agreement not found' }, { status: 404 });
  }

  try {
    const stream = await renderToStream(
      <AgreementDocumentPDF 
        agreement={agreement} 
        tenant={agreement.tenant || {}} 
        apartment={agreement.tenant?.apartment || {}} 
      />
    );

    return new NextResponse(stream as any, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Tenancy_Agreement_${agreement.id}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF Generation Error:", error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}
