import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Link,
  Preview,
  Text,
  Section,
  Button
} from '@react-email/components';
import * as React from 'react';

interface AgreementEmailProps {
  tenantName: string;
  unitName: string;
  agreementUrl: string;
}

export const AgreementEmail = ({
  tenantName = "Valued Tenant",
  unitName = "Your Apartment",
  agreementUrl = "#",
}: AgreementEmailProps) => {
  return (
    <Html>
      <Head />
      <Preview>Your Tenancy Agreement awaits your signature</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>Tenancy Agreement Ready</Heading>
          
          <Text style={text}>
            Hello {tenantName},
          </Text>
          
          <Text style={text}>
            Your application for <strong>{unitName}</strong> has been fully approved, and your official Tenancy Agreement has been generated by the PILAS Properties management team.
          </Text>

          <Section style={section}>
             <Text style={text}>
               Please review the document carefully and provide your digital signature to formalize the lease. You will not be able to access the Tenant Portal entirely until this contract is executed.
             </Text>
          </Section>

          <Section style={buttonContainer}>
            <Button
              style={btn}
              href={agreementUrl}
            >
              Review & Sign Agreement
            </Button>
          </Section>

          <Text style={footer}>
            If you have any questions, please contact administration immediately.
            <br />
            — PILAS Properties Management
          </Text>
        </Container>
      </Body>
    </Html>
  );
};

export default AgreementEmail;

const main = {
  backgroundColor: '#f6f9fc',
  fontFamily:
    '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
};

const h1 = {
  color: '#333',
  fontSize: '24px',
  fontWeight: 'bold',
  padding: '0 48px',
  margin: '30px 0',
};

const text = {
  color: '#525f7f',
  fontSize: '16px',
  lineHeight: '24px',
  padding: '0 48px',
  margin: '16px 0',
};

const section = {
  padding: '0 48px',
};

const buttonContainer = {
  padding: '24px 48px',
  textAlign: 'center' as const,
};

const btn = {
  backgroundColor: '#2563eb',
  borderRadius: '5px',
  color: '#fff',
  fontSize: '16px',
  fontWeight: 'bold',
  textDecoration: 'none',
  display: 'inline-block',
  padding: '12px 20px',
};

const footer = {
  color: '#8898aa',
  fontSize: '12px',
  lineHeight: '16px',
  padding: '0 48px',
  marginTop: '32px',
};
